/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponse } from './userResponse';

export interface BookResponse {
  bookId?: number;
  bookName?: string;
  authorName?: string;
  price?: number;
  stock?: number;
  likedUsers?: UserResponse[];
  likes?: number;
  image?: string;
}
