/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BookRequest {
  /**
   * @minLength 2
   * @maxLength 100
   */
  title: string;
  author: string;
  price: number;
  stock: number;
  image?: string;
}
