/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponse } from './userResponse';
import type { BookResponse } from './bookResponse';

export interface CartResponse {
  user?: UserResponse;
  book?: BookResponse;
  quantity?: number;
}
