/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BookResponse } from './bookResponse';

export interface OrderItemResponse {
  id?: number;
  book?: BookResponse;
  quantity?: number;
  price?: number;
}
